# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fc94a9aa4dd812583e9554452a03c6bc7c27321649d097a9c5c2241cc973ab4286e35adc9fa67b18611918b67ab8b3d641f97d77fb0243e2071536c0b8544b6e

test:
  secret_key_base: 2b3fb4840077635c0bccb1dcaab02a10a980a1e3c74e8762a2199af58d8b4c09f0cd294fb184f257ebda3367ef7302f446141535ae14258405087932e8c64902

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
